const externalData = {

    categories: [
        { name: 'Adventure', value: 12 },
        { name: 'Animation', value: 16 },
        { name: 'Comedy', value: 35 },
        { name: 'Crime', value: 80 },
        { name: 'Documentary', value: 99 },
        { name: 'Drama', value: 18 },
        { name: 'Family', value: 10751 },
        { name: 'Fantasy', value: 14 },
        { name: 'History', value: 36 },
        { name: 'Horror', value: 27 },
        { name: 'Music', value: 10402 },
        { name: 'Mystery', value: 9648 },
        { name: 'Romance', value: 10749 },
        { name: 'Science Fiction', value: 878 },
        { name: 'TV Movie', value: 10770 },
        { name: 'Thriller', value: 53 },
        { name: 'War', value: 10752 }
      ],

      actors: [
        {name: 'Michael Caine', id: 3895},
        {name: 'Morgan Freeman', id: 192},
        {name: 'Leonardo Dicaprio', id: 6193},
        {name: 'Johnny Depp', id: 85},
        {name: 'Clint Eastwood', id: 190},
        {name: 'Christian Bale', id: 3894}, 
        {name: 'Hugh Jackman', id: 6968}, 
        {name: 'Eric Bana', id: 8783}, 
        {name: 'Denzel Washington', id: 5292}, 
        {name: 'Ewan McGregor', id: 3061}, 
        {name: 'Robert Downey Jr.', id: 3223}, 
        {name: 'Jude Law', id: 9642}, 
        {name: 'Bruce Willis', id: 62}, 
        {name: 'Tom Hanks', id: 31}, 
        {name: 'Matt Damon', id: 1892}, 
        {name: 'Will Smith', id: 2888}, 
        {name: 'Ben Stiller', id: 7399}, 
        {name: 'Steve Buscemi', id: 884}, 
        {name: 'Ron Perlman', id: 2372}, 
        {name: 'Ian McKellen', id: 1327}, 
        {name: 'Christopher Lee', id: 113}, 
        {name: 'Liam Neeson', id: 3896}, 
        {name: 'Willem Dafoe', id: 5293}, 
        {name: 'Robert De Niro', id: 380}, 
        {name: 'Al Pacino', id: 1158}, 
        {name: 'Anthony Hopkins', id: 4173}, 
        {name: 'Robin Williams', id: 2157}, 
        {name: 'Ben Kingsley', id: 2282}, 
        {name: 'Kevin Spacey', id: 1979}, 
        {name: 'Joaquin Phoenix', id: 73421}, 
        {name: 'Brad Pitt', id: 287}, 
        {name: 'Tom Cruise', id: 500}, 
      ]
}

export default externalData